name: Flamingo CD

on: 
  push:
    branches: [master]

jobs:
  beta_apk:
    # name: Upload android beta to Firebase App Distribution.
    # needs: [build]
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: release-apk
    - name: Upload APK
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        group: testers
        file: app-release.apk